export interface ApiParam {
  name: string
  type: 'string' | 'number' | 'boolean'
  defaultValue: string
  required: boolean
  description: string
}

export interface ApiItem {
  id: string | number
  name: string
  url: string
  method: 'GET' | 'POST'
  category: string
  description: string
  params: ApiParam[]
  createdAt?: string
  pinned?: boolean
  userCreated?: boolean
}

export const defaultApis: ApiItem[] = [
  {
    id: 1,
    name: '随机笑话',
    url: 'https://official-joke-api.appspot.com/random_joke',
    method: 'GET',
    category: '娱乐',
    description: '获取一个随机的英文笑话',
    params: [],
    pinned: false,
  },
  {
    id: 2,
    name: '随机猫咪图片',
    url: 'https://api.thecatapi.com/v1/images/search',
    method: 'GET',
    category: '图片',
    description: '获取一张随机的猫咪图片',
    params: [],
    pinned: false,
  },
  {
    id: 3,
    name: '随机狗狗图片',
    url: 'https://dog.ceo/api/breeds/image/random',
    method: 'GET',
    category: '图片',
    description: '获取一张随机的狗狗图片',
    params: [],
    pinned: false,
  },
  {
    id: 4,
    name: '获取用户信息',
    url: 'https://jsonplaceholder.typicode.com/users/1',
    method: 'GET',
    category: '测试',
    description: '获取JSONPlaceholder的用户信息（测试用）',
    params: [],
    pinned: false,
  },
  {
    id: 6,
    name: 'GitHub用户信息',
    url: 'https://api.github.com/users/{username}',
    method: 'GET',
    category: '开发',
    description: '通过用户名获取GitHub用户信息',
    params: [
      {
        name: 'username',
        type: 'string',
        defaultValue: 'octocat',
        required: true,
        description: 'GitHub用户名',
      },
    ],
    pinned: false,
  },
  {
    id: 7,
    name: '天气查询',
    url: 'https://wttr.in/{city}?format=j1',
    method: 'GET',
    category: '工具',
    description: '查询指定城市的天气信息',
    params: [
      {
        name: 'city',
        type: 'string',
        defaultValue: 'Beijing',
        required: true,
        description: '城市名称（英文）',
      },
    ],
    pinned: false,
  },
  {
    id: 9,
    name: '随机狐狸图片',
    url: 'https://randomfox.ca/floof/',
    method: 'GET',
    category: '图片',
    description: '返回一张随机狐狸图片的 URL（JSON）',
    params: [],
    pinned: false,
  },
  {
    id: 10,
    name: '随机猫咪图片(Cataas)',
    url: 'https://cataas.com/cat?json=true',
    method: 'GET',
    category: '图片',
    description: '返回一张随机猫咪图片（JSON，含图片地址）',
    params: [],
    pinned: false,
  },
  {
    id: 11,
    name: '随机动漫图片',
    url: 'https://nekos.life/api/v2/img/{type}',
    method: 'GET',
    category: '图片',
    description: '返回随机动漫图片 URL，type 可选 neko/kitsune 等',
    params: [
      {
        name: 'type',
        type: 'string',
        defaultValue: 'neko',
        required: true,
        description: '图片类型，如 neko/kitsune',
      },
    ],
    pinned: false,
  },
  {
    id: 12,
    name: '卡通头像(DiceBear)',
    url: 'https://api.dicebear.com/7.x/{style}/svg?seed={seed}',
    method: 'GET',
    category: '图片',
    description: '按 seed 生成卡通头像 SVG（style 可选 bottts/personas 等）',
    params: [
      {
        name: 'style',
        type: 'string',
        defaultValue: 'bottts',
        required: true,
        description: '头像风格，如 bottts/personas/adventurer',
      },
      {
        name: 'seed',
        type: 'string',
        defaultValue: 'demo',
        required: false,
        description: '随机种子，相同种子生成相同头像',
      },
    ],
    pinned: false,
  },
  {
    id: 13,
    name: '机器人头像(RoboHash)',
    url: 'https://robohash.org/{text}.png',
    method: 'GET',
    category: '图片',
    description: '按文本哈希生成机器人/怪物头像图片',
    params: [
      {
        name: 'text',
        type: 'string',
        defaultValue: 'demo',
        required: true,
        description: '用于生成头像的文本',
      },
    ],
    pinned: false,
  },
  {
    id: 14,
    name: '随机用户资料',
    url: 'https://randomuser.me/api/?results={results}&gender={gender}',
    method: 'GET',
    category: '图片',
    description: '返回随机用户资料（含头像 URL），可选 results/gender',
    params: [
      {
        name: 'results',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '返回用户数量',
      },
      {
        name: 'gender',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '性别筛选，male/female',
      },
    ],
    pinned: false,
  },
  {
    id: 15,
    name: '必应每日壁纸',
    url: 'https://bing.biturl.top/?resolution=1920&format=json&index=0&mkt=zh-CN',
    method: 'GET',
    category: '图片',
    description: '返回当日必应壁纸图片地址与版权说明（国内可直连）',
    params: [],
    pinned: false,
  },
  {
    id: 16,
    name: '爸爸冷笑话',
    url: 'https://icanhazdadjoke.com/',
    method: 'GET',
    category: '娱乐',
    description: '返回一条英文冷笑话（需 Accept: application/json，本应用默认已带）',
    params: [],
    pinned: false,
  },
  {
    id: 17,
    name: '每日冷知识',
    url: 'https://uselessfacts.jsph.pl/api/v2/facts/random?language=en',
    method: 'GET',
    category: '娱乐',
    description: '返回一条无用的冷知识（英文）',
    params: [],
    pinned: false,
  },
  {
    id: 18,
    name: '侃爷语录',
    url: 'https://api.kanye.rest',
    method: 'GET',
    category: '娱乐',
    description: '返回一句 Kanye West 随机语录',
    params: [],
    pinned: false,
  },
  {
    id: 19,
    name: '随机生活建议',
    url: 'https://api.adviceslip.com/advice',
    method: 'GET',
    category: '娱乐',
    description: '返回一条随机生活建议',
    params: [],
    pinned: false,
  },
  {
    id: 20,
    name: 'Ron Swanson 名言',
    url: 'https://ron-swanson-quotes.herokuapp.com/v2/quotes',
    method: 'GET',
    category: '娱乐',
    description: '返回一句 Ron Swanson 台词（数组）',
    params: [],
    pinned: false,
  },
  {
    id: 21,
    name: '分类随机笑话',
    url: 'https://v2.jokeapi.dev/joke/Any?type=single',
    method: 'GET',
    category: '娱乐',
    description: '按分类返回随机笑话（single 两段式可选）',
    params: [],
    pinned: false,
  },
  {
    id: 22,
    name: '猫咪趣味事实',
    url: 'https://meowfacts.herokuapp.com/?count=1',
    method: 'GET',
    category: '娱乐',
    description: '返回一条关于猫的趣味事实',
    params: [],
    pinned: false,
  },
  {
    id: 23,
    name: '猫咪冷知识',
    url: 'https://catfact.ninja/fact',
    method: 'GET',
    category: '娱乐',
    description: '返回一条随机猫咪冷知识',
    params: [],
    pinned: false,
  },
  {
    id: 24,
    name: '一言',
    url: 'https://v1.hitokoto.cn/?c=d',
    method: 'GET',
    category: '娱乐',
    description: '返回随机一句名言/语录，支持分类（国内可直连）',
    params: [],
    pinned: false,
  },
  {
    id: 25,
    name: '今日诗词',
    url: 'https://v1.jinrishici.com/all.json',
    method: 'GET',
    category: '娱乐',
    description: '返回随机一句古诗文，含作者与出处（国内可直连）',
    params: [],
    pinned: false,
  },
  {
    id: 26,
    name: 'IP 地理查询',
    url: 'https://ipwho.is/{ip}',
    method: 'GET',
    category: '工具',
    description: '按 IP 查询国家/城市/经纬度/时区（留空查本机）',
    params: [
      {
        name: 'ip',
        type: 'string',
        defaultValue: '',
        required: true,
        description: 'IP 地址，留空则查询当前 IP',
      },
    ],
    pinned: false,
  },
  {
    id: 27,
    name: '二维码生成',
    url: 'https://api.qrserver.com/v1/create-qr-code/?data={data}&size={size}',
    method: 'GET',
    category: '工具',
    description: '生成二维码 PNG 图片，data 为内容，size 如 200x200',
    params: [
      {
        name: 'data',
        type: 'string',
        defaultValue: 'https://vuechest.com',
        required: true,
        description: '二维码内容',
      },
      {
        name: 'size',
        type: 'string',
        defaultValue: '200x200',
        required: false,
        description: '尺寸，如 200x200',
      },
    ],
    pinned: false,
  },
  {
    id: 28,
    name: 'UUID 生成',
    url: 'https://www.uuidtools.com/api/generate/v1',
    method: 'GET',
    category: '工具',
    description: '返回随机 UUID 字符串数组',
    params: [],
    pinned: false,
  },
  {
    id: 29,
    name: '姓名年龄预测',
    url: 'https://api.agify.io?name={name}',
    method: 'GET',
    category: '工具',
    description: '根据姓名预测年龄段',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'michael',
        required: true,
        description: '姓名',
      },
    ],
    pinned: false,
  },
  {
    id: 30,
    name: '姓名性别预测',
    url: 'https://api.genderize.io?name={name}',
    method: 'GET',
    category: '工具',
    description: '根据姓名预测性别',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'mary',
        required: true,
        description: '姓名',
      },
    ],
    pinned: false,
  },
  {
    id: 31,
    name: '姓名国籍预测',
    url: 'https://api.nationalize.io?name={name}',
    method: 'GET',
    category: '工具',
    description: '根据姓名预测最可能国籍',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'nathaniel',
        required: true,
        description: '姓名',
      },
    ],
    pinned: false,
  },
  {
    id: 33,
    name: '开放图书馆检索',
    url: 'https://openlibrary.org/search.json?q={query}&limit={limit}',
    method: 'GET',
    category: '数据',
    description: '开放图书馆图书检索，返回书籍元数据',
    params: [
      {
        name: 'query',
        type: 'string',
        defaultValue: 'harry potter',
        required: true,
        description: '搜索关键词',
      },
      {
        name: 'limit',
        type: 'number',
        defaultValue: '5',
        required: false,
        description: '返回条数',
      },
    ],
    pinned: false,
  },
  {
    id: 34,
    name: '公共节假日查询',
    url: 'https://date.nager.at/api/v3/PublicHolidays/{year}/{countryCode}',
    method: 'GET',
    category: '数据',
    description: '查询指定年份与国家代码的公共节假日',
    params: [
      {
        name: 'year',
        type: 'string',
        defaultValue: '2025',
        required: true,
        description: '年份，如 2025',
      },
      {
        name: 'countryCode',
        type: 'string',
        defaultValue: 'CN',
        required: true,
        description: '国家代码，如 CN/US',
      },
    ],
    pinned: false,
  },
  {
    id: 35,
    name: '全球物种数据库',
    url: 'https://api.gbif.org/v1/species/{key}',
    method: 'GET',
    category: '数据',
    description: '全球物种数据库，按物种 key 查询信息',
    params: [
      {
        name: 'key',
        type: 'string',
        defaultValue: '1',
        required: true,
        description: '物种 key，如 1',
      },
    ],
    pinned: false,
  },
  {
    id: 36,
    name: '加密货币行情',
    url: 'https://api.coinbase.com/v2/prices/{pair}/spot',
    method: 'GET',
    category: '数据',
    description: '查询加密货币现货价格，pair 如 BTC-USD',
    params: [
      {
        name: 'pair',
        type: 'string',
        defaultValue: 'BTC-USD',
        required: true,
        description: '交易对，如 BTC-USD',
      },
    ],
    pinned: false,
  },
  {
    id: 37,
    name: 'Chuck Norris 笑话',
    url: 'https://api.chucknorris.io/jokes/random',
    method: 'GET',
    category: '娱乐',
    description: '随机返回一条 Chuck Norris 风格的搞笑段子',
    params: [],
    pinned: false,
  },
  {
    id: 38,
    name: '动漫随机名言',
    url: 'https://api.animechan.io/v1/quotes/random',
    method: 'GET',
    category: '娱乐',
    description: '随机返回一句动漫台词及其出处与角色',
    params: [],
    pinned: false,
  },
  {
    id: 39,
    name: '随机梗图',
    url: 'https://meme-api.com/gimme',
    method: 'GET',
    category: '娱乐',
    description: '随机返回一张来自 Reddit 的搞笑梗图（含图片地址与标题）',
    params: [],
    pinned: false,
  },
  {
    id: 40,
    name: '趣味知识问答',
    url: 'https://opentdb.com/api.php?amount={amount}',
    method: 'GET',
    category: '娱乐',
    description: 'Open Trivia DB 随机题库，返回选择题与答案',
    params: [
      {
        name: 'amount',
        type: 'number',
        defaultValue: '1',
        required: true,
        description: '返回的题目数量',
      },
    ],
    pinned: false,
  },
  {
    id: 41,
    name: '随机鸡尾酒配方',
    url: 'https://www.thecocktaildb.com/api/json/v1/1/random.php',
    method: 'GET',
    category: '娱乐',
    description: '随机返回一款鸡尾酒的名称、配方与做法',
    params: [],
    pinned: false,
  },
  {
    id: 42,
    name: '随机菜谱',
    url: 'https://www.themealdb.com/api/json/v1/1/random.php',
    method: 'GET',
    category: '娱乐',
    description: '随机返回一道菜的名称、食材与制作步骤',
    params: [],
    pinned: false,
  },
  {
    id: 43,
    name: '随机精酿啤酒厂',
    url: 'https://api.openbrewerydb.org/v1/breweries/random',
    method: 'GET',
    category: '娱乐',
    description: '随机返回一家精酿啤酒厂的信息（名称、地点、类型）',
    params: [],
    pinned: false,
  },
  {
    id: 44,
    name: '吉卜力电影资料',
    url: 'https://ghibliapi.vercel.app/films',
    method: 'GET',
    category: '娱乐',
    description: '返回吉卜力工作室全部电影列表（标题、导演、简介等）',
    params: [],
    pinned: false,
  },
  {
    id: 45,
    name: '哈利波特角色',
    url: 'https://hp-api.onrender.com/api/characters',
    method: 'GET',
    category: '娱乐',
    description: '返回《哈利波特》全部角色资料（姓名、学院、扮演者等）',
    params: [],
    pinned: false,
  },
  {
    id: 46,
    name: '瑞克和莫蒂角色',
    url: 'https://rickandmortyapi.com/api/character/{id}',
    method: 'GET',
    category: '娱乐',
    description: '按 ID 返回《瑞克和莫蒂》角色资料',
    params: [
      {
        name: 'id',
        type: 'number',
        defaultValue: '1',
        required: true,
        description: '角色 ID，范围 1-826',
      },
    ],
    pinned: false,
  },
  {
    id: 47,
    name: '宝可梦资料',
    url: 'https://pokeapi.co/api/v2/pokemon/{name}',
    method: 'GET',
    category: '娱乐',
    description: '按名称或 ID 查询宝可梦的属性、技能与形象',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'ditto',
        required: true,
        description: '宝可梦英文名或 ID，如 ditto、pikachu、25',
      },
    ],
    pinned: false,
  },
  {
    id: 48,
    name: '星球大战人物',
    url: 'https://swapi.dev/api/people/{id}',
    method: 'GET',
    category: '娱乐',
    description: '按 ID 返回《星球大战》人物资料（姓名、身高、出生年份等）',
    params: [
      {
        name: 'id',
        type: 'number',
        defaultValue: '1',
        required: true,
        description: '人物 ID，范围 1-82',
      },
    ],
    pinned: false,
  },
  {
    id: 49,
    name: 'Lorem Picsum 随机图片',
    url: 'https://picsum.photos/{width}/{height}',
    method: 'GET',
    category: '图片',
    description: '从 Picsum 图库随机返回一张指定尺寸的图片，免费无需 Key',
    params: [
      {
        name: 'width',
        type: 'number',
        defaultValue: '400',
        required: true,
        description: '图片宽度(像素)',
      },
      {
        name: 'height',
        type: 'number',
        defaultValue: '300',
        required: true,
        description: '图片高度(像素)',
      },
    ],
    pinned: false,
  },
  {
    id: 50,
    name: 'Picsum 种子图片',
    url: 'https://picsum.photos/seed/{seed}/{width}/{height}',
    method: 'GET',
    category: '图片',
    description: '用固定 seed 生成可复现的随机图片，相同 seed 永远返回同一张图',
    params: [
      {
        name: 'seed',
        type: 'string',
        defaultValue: 'vuechest',
        required: true,
        description: '随机种子，决定返回哪张图',
      },
      {
        name: 'width',
        type: 'number',
        defaultValue: '400',
        required: true,
        description: '图片宽度(像素)',
      },
      {
        name: 'height',
        type: 'number',
        defaultValue: '300',
        required: true,
        description: '图片高度(像素)',
      },
    ],
    pinned: false,
  },
  {
    id: 51,
    name: 'Picsum 图片图库',
    url: 'https://picsum.photos/v2/list?page={page}&limit={limit}',
    method: 'GET',
    category: '图片',
    description: '分页返回图片元数据列表(JSON)，含作者信息与原图下载地址，适合做画廊',
    params: [
      {
        name: 'page',
        type: 'number',
        defaultValue: '1',
        required: true,
        description: '页码，从 1 开始',
      },
      {
        name: 'limit',
        type: 'number',
        defaultValue: '10',
        required: true,
        description: '每页返回数量(最大100)',
      },
    ],
    pinned: false,
  },
  {
    id: 52,
    name: 'LoremFlickr 关键词图片',
    url: 'https://loremflickr.com/{width}/{height}/{keywords}',
    method: 'GET',
    category: '图片',
    description: '按关键词(英文标签)随机返回 Flickr 上的真实照片，免费无需 Key',
    params: [
      {
        name: 'width',
        type: 'number',
        defaultValue: '400',
        required: true,
        description: '图片宽度(像素)',
      },
      {
        name: 'height',
        type: 'number',
        defaultValue: '300',
        required: true,
        description: '图片高度(像素)',
      },
      {
        name: 'keywords',
        type: 'string',
        defaultValue: 'cat,dog',
        required: true,
        description: '英文关键词，逗号分隔，如 cat,dog',
      },
    ],
    pinned: false,
  },
  {
    id: 53,
    name: 'DummyImage 占位图',
    url: 'https://dummyimage.com/{width}x{height}/{bg}/{fg}&text={text}',
    method: 'GET',
    category: '图片',
    description: '生成自定义尺寸/颜色/文字的占位图，常用于界面原型与开发调试',
    params: [
      {
        name: 'width',
        type: 'number',
        defaultValue: '400',
        required: true,
        description: '图片宽度(像素)',
      },
      {
        name: 'height',
        type: 'number',
        defaultValue: '300',
        required: true,
        description: '图片高度(像素)',
      },
      {
        name: 'bg',
        type: 'string',
        defaultValue: '0099ff',
        required: true,
        description: '背景色，十六进制不含#，如 0099ff',
      },
      {
        name: 'fg',
        type: 'string',
        defaultValue: 'ffffff',
        required: true,
        description: '前景/文字颜色，十六进制不含#，如 ffffff',
      },
      {
        name: 'text',
        type: 'string',
        defaultValue: 'VueChest',
        required: false,
        description: '图上显示的文字',
      },
    ],
    pinned: false,
  },
  {
    id: 54,
    name: 'Placehold 占位图',
    url: 'https://placehold.co/{width}x{height}?text={text}',
    method: 'GET',
    category: '图片',
    description: '生成简洁的占位图，支持自定义文字与尺寸，免费无需 Key',
    params: [
      {
        name: 'width',
        type: 'number',
        defaultValue: '400',
        required: true,
        description: '图片宽度(像素)',
      },
      {
        name: 'height',
        type: 'number',
        defaultValue: '300',
        required: true,
        description: '图片高度(像素)',
      },
      {
        name: 'text',
        type: 'string',
        defaultValue: 'VueChest',
        required: false,
        description: '图上显示的文字',
      },
    ],
    pinned: false,
  },
  {
    id: 55,
    name: 'RandomDog 随机狗图',
    url: 'https://random.dog/woof.json',
    method: 'GET',
    category: '图片',
    description: '随机返回一只狗的图片或视频地址(JSON)，可爱解压用',
    params: [],
    pinned: false,
  },
  {
    id: 56,
    name: 'UI Avatars 文字头像',
    url: 'https://ui-avatars.com/api/?name={name}&size={size}',
    method: 'GET',
    category: '图片',
    description: '根据姓名首字母生成圆形头像图片，适合做默认用户头像',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'Vue Chest',
        required: true,
        description: '姓名，取首字母生成头像',
      },
      {
        name: 'size',
        type: 'number',
        defaultValue: '128',
        required: true,
        description: '头像像素尺寸',
      },
    ],
    pinned: false,
  },
  {
    id: 57,
    name: 'wsrv.nl 图片代理处理',
    url: 'https://wsrv.nl/?url={imageUrl}&w={width}',
    method: 'GET',
    category: '工具',
    description: '图片代理与处理服务，可对任意外链图片做缩放/格式转换，解决跨域与尺寸问题',
    params: [
      {
        name: 'imageUrl',
        type: 'string',
        defaultValue: 'https://picsum.photos/400/300',
        required: true,
        description: '待处理的图片完整 URL(不含协议前缀也可)',
      },
      {
        name: 'width',
        type: 'number',
        defaultValue: '300',
        required: true,
        description: '输出图片宽度(像素)',
      },
    ],
    pinned: false,
  },
  {
    id: 58,
    name: '颜色查询',
    url: 'https://www.thecolorapi.com/id?hex={hex}',
    method: 'GET',
    category: '工具',
    description: '根据 HEX 颜色值返回颜色名称、RGB、HSL、CMYK 等详细信息',
    params: [
      {
        name: 'hex',
        type: 'string',
        defaultValue: '4e79a7',
        required: false,
        description: '十六进制颜色值（不含 #）',
      },
    ],
    pinned: false,
  },
  {
    id: 59,
    name: '条形码生成',
    url: 'https://barcodeapi.org/api/{format}/{data}',
    method: 'GET',
    category: '工具',
    description: '生成指定格式（Code128/EAN13/UPC 等）的条形码 SVG 图片',
    params: [
      {
        name: 'format',
        type: 'string',
        defaultValue: 'code128',
        required: false,
        description: '条码格式，如 code128、ean13、upc',
      },
      {
        name: 'data',
        type: 'string',
        defaultValue: 'hello',
        required: true,
        description: '要编码到条形码中的内容',
      },
    ],
    pinned: false,
  },
  {
    id: 60,
    name: '邮编查询',
    url: 'https://api.zippopotam.us/{country}/{zip}',
    method: 'GET',
    category: '地理',
    description: '根据国家和邮政编码查询对应的城市、州省及经纬度等地址信息',
    params: [
      {
        name: 'country',
        type: 'string',
        defaultValue: 'us',
        required: true,
        description: '国家代码，如 us、de、gb',
      },
      {
        name: 'zip',
        type: 'string',
        defaultValue: '90210',
        required: true,
        description: '邮政编码',
      },
    ],
    pinned: false,
  },
  {
    id: 61,
    name: '假REST数据',
    url: 'https://jsonplaceholder.typicode.com/{resource}/{id}',
    method: 'GET',
    category: '开发',
    description: '提供可用于原型与测试的假 REST 数据（todos/users/posts/comments 等）',
    params: [
      {
        name: 'resource',
        type: 'string',
        defaultValue: 'todos',
        required: false,
        description: '资源名，如 todos、users、posts',
      },
      {
        name: 'id',
        type: 'string',
        defaultValue: '1',
        required: false,
        description: '资源 ID',
      },
    ],
    pinned: false,
  },
  {
    id: 62,
    name: 'HTTP测试',
    url: 'https://httpbin.org/{path}',
    method: 'GET',
    category: '开发',
    description: 'HTTP 请求/响应调试工具，回显请求头、客户端 IP、参数等信息',
    params: [
      {
        name: 'path',
        type: 'string',
        defaultValue: 'get',
        required: false,
        description: '端点路径，如 get、ip、headers、uuid',
      },
    ],
    pinned: false,
  },
  {
    id: 63,
    name: '假数据(商品/用户)',
    url: 'https://dummyjson.com/{resource}/{id}',
    method: 'GET',
    category: '开发',
    description: '提供商品、用户、购物车等结构化假数据，适合前端开发联调',
    params: [
      {
        name: 'resource',
        type: 'string',
        defaultValue: 'products',
        required: false,
        description: '资源名，如 products、users、carts',
      },
      {
        name: 'id',
        type: 'string',
        defaultValue: '1',
        required: false,
        description: '资源 ID',
      },
    ],
    pinned: false,
  },
  {
    id: 64,
    name: '假电商数据',
    url: 'https://fakestoreapi.com/products/{id}',
    method: 'GET',
    category: '数据',
    description: '提供电商场景的假商品数据（含价格、图片、分类），用于演示与测试',
    params: [
      {
        name: 'id',
        type: 'string',
        defaultValue: '1',
        required: false,
        description: '商品 ID，留空可不传以获取列表',
      },
    ],
    pinned: false,
  },
  {
    id: 65,
    name: '趣味占位文本',
    url: 'https://baconipsum.com/api/?type={type}&sentences={sentences}',
    method: 'GET',
    category: '工具',
    description: '生成以培根为主题的趣味占位文本（Lorem Ipsum 变体），返回纯文本',
    params: [
      {
        name: 'type',
        type: 'string',
        defaultValue: 'all-meat',
        required: false,
        description: '文本类型，如 all-meat、meat-and-filler',
      },
      {
        name: 'sentences',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '生成句子数量',
      },
    ],
    pinned: false,
  },
  {
    id: 66,
    name: '真随机数',
    url: 'https://www.random.org/integers/?num={num}&min={min}&max={max}&col=1&base=10&format=plain&rnd=new',
    method: 'GET',
    category: '工具',
    description: '基于大气噪声生成真随机数，返回指定范围的随机整数（纯文本）',
    params: [
      {
        name: 'num',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '生成随机数的个数',
      },
      {
        name: 'min',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '最小值',
      },
      {
        name: 'max',
        type: 'number',
        defaultValue: '100',
        required: false,
        description: '最大值',
      },
    ],
    pinned: false,
  },
  {
    id: 67,
    name: '当前时间日期',
    url: 'https://timeapi.io/api/Time/current/zone?timeZone={timeZone}',
    method: 'GET',
    category: '工具',
    description: '根据 IANA 时区返回当前的日期、时间、星期与 Unix 时间戳',
    params: [
      {
        name: 'timeZone',
        type: 'string',
        defaultValue: 'Asia/Shanghai',
        required: false,
        description: 'IANA 时区，如 Asia/Shanghai、Europe/London',
      },
    ],
    pinned: false,
  },
  {
    id: 68,
    name: '公网IP查询 (ipify)',
    url: 'https://api.ipify.org?format={format}',
    method: 'GET',
    category: '地理',
    description: '获取当前设备的公网 IP 地址，无需 Key、支持 CORS',
    params: [
      {
        name: 'format',
        type: 'string',
        defaultValue: 'json',
        required: false,
        description: '返回格式，json 或 text',
      },
    ],
    pinned: false,
  },
  {
    id: 69,
    name: 'IP地理定位 (geojs)',
    url: 'https://get.geojs.io/v1/ip/geo/{ip}.json',
    method: 'GET',
    category: '地理',
    description: '根据 IP 查询国家、城市、经纬度等地理位置信息',
    params: [
      {
        name: 'ip',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '目标 IP，留空则查询请求者自身 IP',
      },
    ],
    pinned: false,
  },
  {
    id: 70,
    name: 'IP信息查询 (ip.sb)',
    url: 'https://api.ip.sb/geoip/{ip}',
    method: 'GET',
    category: '地理',
    description: '根据 IP 查询 ASN、城市、经纬度等网络与地理信息',
    params: [
      {
        name: 'ip',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '目标 IP，留空则查询请求者自身 IP',
      },
    ],
    pinned: false,
  },
  {
    id: 71,
    name: 'IP归属国家 (country.is)',
    url: 'https://api.country.is/{ip}',
    method: 'GET',
    category: '地理',
    description: '根据 IP 快速查询所属 ISO 国家代码',
    params: [
      {
        name: 'ip',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '目标 IP，留空则查询请求者自身 IP',
      },
    ],
    pinned: false,
  },
  {
    id: 72,
    name: '天气预报 (Open-Meteo)',
    url: 'https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&current_weather={current_weather}',
    method: 'GET',
    category: '地理',
    description: '免 Key 的天气预报，支持当前、逐小时与逐日数据',
    params: [
      {
        name: 'latitude',
        type: 'number',
        defaultValue: '39.9042',
        required: true,
        description: '纬度，如北京 39.9042',
      },
      {
        name: 'longitude',
        type: 'number',
        defaultValue: '116.4074',
        required: true,
        description: '经度，如北京 116.4074',
      },
      {
        name: 'current_weather',
        type: 'string',
        defaultValue: 'true',
        required: false,
        description: '是否返回当前天气',
      },
    ],
    pinned: false,
  },
  {
    id: 73,
    name: '地理编码 (Open-Meteo)',
    url: 'https://geocoding-api.open-meteo.com/v1/search?name={name}&count={count}',
    method: 'GET',
    category: '地理',
    description: '按城市/地名搜索并返回经纬度等地理编码结果',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'Beijing',
        required: true,
        description: '要搜索的地名或城市',
      },
      {
        name: 'count',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '返回结果数量',
      },
    ],
    pinned: false,
  },
  {
    id: 74,
    name: '邮编查位置 (Zippopotam)',
    url: 'https://api.zippopotam.us/{country}/{postcode}',
    method: 'GET',
    category: '地理',
    description: '通过邮编查询地理位置，支持多国（us/de/gb 等）',
    params: [
      {
        name: 'country',
        type: 'string',
        defaultValue: 'us',
        required: true,
        description: '国家代码，如 us、de、gb',
      },
      {
        name: 'postcode',
        type: 'string',
        defaultValue: '90210',
        required: true,
        description: '邮政编码',
      },
    ],
    pinned: false,
  },
  {
    id: 75,
    name: '英国邮编查询 (postcodes.io)',
    url: 'https://api.postcodes.io/postcodes/{postcode}',
    method: 'GET',
    category: '地理',
    description: '查询英国邮编对应的经纬度、地区与行政区划',
    params: [
      {
        name: 'postcode',
        type: 'string',
        defaultValue: 'SW1A1AA',
        required: true,
        description: '英国邮政编码',
      },
    ],
    pinned: false,
  },
  {
    id: 76,
    name: '日出日落时间',
    url: 'https://api.sunrise-sunset.org/json?lat={lat}&lng={lng}',
    method: 'GET',
    category: '地理',
    description: '根据经纬度查询指定日期的日出、日落与黄金时刻',
    params: [
      {
        name: 'lat',
        type: 'number',
        defaultValue: '36.72',
        required: true,
        description: '纬度',
      },
      {
        name: 'lng',
        type: 'number',
        defaultValue: '-94.84',
        required: true,
        description: '经度',
      },
    ],
    pinned: false,
  },
  {
    id: 77,
    name: '汇率换算 (Frankfurter)',
    url: 'https://api.frankfurter.app/latest?from={from}&to={to}',
    method: 'GET',
    category: '地理',
    description: '基于欧洲央行数据的免 Key 汇率换算',
    params: [
      {
        name: 'from',
        type: 'string',
        defaultValue: 'USD',
        required: false,
        description: '源货币代码，如 USD',
      },
      {
        name: 'to',
        type: 'string',
        defaultValue: 'CNY',
        required: false,
        description: '目标货币代码，如 CNY，可多选用逗号分隔',
      },
    ],
    pinned: false,
  },
  {
    id: 78,
    name: '实时汇率 (ExchangeRate)',
    url: 'https://open.er-api.com/v6/latest/{base}',
    method: 'GET',
    category: '地理',
    description: '免 Key 的实时多币种汇率，返回以 base 为基准的全部汇率',
    params: [
      {
        name: 'base',
        type: 'string',
        defaultValue: 'USD',
        required: true,
        description: '基准货币代码，如 USD、CNY',
      },
    ],
    pinned: false,
  },
  {
    id: 79,
    name: '维基百科摘要',
    url: 'https://en.wikipedia.org/api/rest_v1/page/summary/{title}',
    method: 'GET',
    category: '数据',
    description: '获取维基百科词条的标题、简介与缩略图，无需 Key、支持 CORS',
    params: [
      {
        name: 'title',
        type: 'string',
        defaultValue: 'NASA',
        required: true,
        description: '词条标题，支持空格（会自动编码），如 Albert Einstein',
      },
    ],
    pinned: false,
  },
  {
    id: 80,
    name: '免费英语词典',
    url: 'https://api.dictionaryapi.dev/api/v2/entries/en/{word}',
    method: 'GET',
    category: '数据',
    description: '查询英语单词的发音、词性与释义，基于 Wiktionary，支持 CORS',
    params: [
      {
        name: 'word',
        type: 'string',
        defaultValue: 'hello',
        required: true,
        description: '要查询的英文单词',
      },
    ],
    pinned: false,
  },
  {
    id: 81,
    name: '大都会艺术博物馆',
    url: 'https://collectionapi.metmuseum.org/public/collection/v1/objects/{id}',
    method: 'GET',
    category: '数据',
    description: '按编号获取纽约大都会博物馆藏品信息（作者、年代、高清图片）',
    params: [
      {
        name: 'id',
        type: 'string',
        defaultValue: '1',
        required: true,
        description: '藏品编号，可先用 /public/collection/v1/objects 获取全部编号列表',
      },
    ],
    pinned: false,
  },
  {
    id: 82,
    name: '太空新闻',
    url: 'https://api.spaceflightnewsapi.net/v4/articles/?search={search}&limit={limit}',
    method: 'GET',
    category: '数据',
    description: '获取最新太空与航天新闻文章（标题、摘要、来源、图片）',
    params: [
      {
        name: 'search',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '关键词搜索，留空返回最新文章列表',
      },
      {
        name: 'limit',
        type: 'number',
        defaultValue: '10',
        required: false,
        description: '返回文章数量上限',
      },
    ],
    pinned: false,
  },
  {
    id: 83,
    name: '火箭发射计划',
    url: 'https://ll.thespacedevs.com/2.2.0/launch/upcoming/?limit={limit}',
    method: 'GET',
    category: '数据',
    description: '获取即将进行的全球火箭发射计划（时间、火箭、发射台）',
    params: [
      {
        name: 'limit',
        type: 'number',
        defaultValue: '5',
        required: false,
        description: '返回发射条目数量上限',
      },
    ],
    pinned: false,
  },
  {
    id: 84,
    name: '音乐百科 MusicBrainz',
    url: 'https://musicbrainz.org/ws/2/recording/?query={query}&fmt=json',
    method: 'GET',
    category: '数据',
    description: '搜索音乐录音/曲目信息（艺人、专辑、发行信息），免费开放数据',
    params: [
      {
        name: 'query',
        type: 'string',
        defaultValue: 'Love',
        required: true,
        description: '曲目或艺人搜索关键词',
      },
    ],
    pinned: false,
  },
  {
    id: 85,
    name: '单词联想 Datamuse',
    url: 'https://api.datamuse.com/words?rel_rhy={word}',
    method: 'GET',
    category: '数据',
    description: '按押韵/同义/关联等关系查询英文单词，适合写作与词汇扩展',
    params: [
      {
        name: 'word',
        type: 'string',
        defaultValue: 'test',
        required: true,
        description: '基准词；rel_rhy 表示查询与其押韵的单词',
      },
    ],
    pinned: false,
  },
  {
    id: 86,
    name: '开放食物库',
    url: 'https://world.openfoodfacts.org/api/v2/product/{barcode}.json',
    method: 'GET',
    category: '数据',
    description: '按条形码查询食品的营养成分、配料与标签等开放数据',
    params: [
      {
        name: 'barcode',
        type: 'string',
        defaultValue: '737628064502',
        required: true,
        description: '商品条形码（EAN/UPC）',
      },
    ],
    pinned: false,
  },
  {
    id: 87,
    name: '圣经经文',
    url: 'https://bible-api.com/{reference}',
    method: 'GET',
    category: '数据',
    description: '按书卷章节获取圣经经文文本，支持多译本（如 ?translation=kjv）',
    params: [
      {
        name: 'reference',
        type: 'string',
        defaultValue: 'john 3:16',
        required: true,
        description: '经文引用，如 john 3:16 或 romans 8',
      },
    ],
    pinned: false,
  },
  {
    id: 88,
    name: '电视节目搜索 TVMaze',
    url: 'https://api.tvmaze.com/search/shows?q={q}',
    method: 'GET',
    category: '娱乐',
    description: '搜索电视剧/节目信息，含剧情简介、评分与海报图片',
    params: [
      {
        name: 'q',
        type: 'string',
        defaultValue: 'batman',
        required: true,
        description: '节目名称搜索关键词',
      },
    ],
    pinned: false,
  },
  {
    id: 89,
    name: '全球食谱',
    url: 'https://www.themealdb.com/api/json/v1/1/search.php?s={s}',
    method: 'GET',
    category: '数据',
    description: '按名称搜索全球食谱，返回食材、做法步骤与成品图片',
    params: [
      {
        name: 's',
        type: 'string',
        defaultValue: 'chicken',
        required: true,
        description: '食谱名称关键词；用 s= 空字符串可随机浏览',
      },
    ],
    pinned: false,
  },
  {
    id: 90,
    name: 'CoinGecko 加密货币价格',
    url: 'https://api.coingecko.com/api/v3/simple/price?ids={ids}&vs_currencies={vs}',
    method: 'GET',
    category: '金融',
    description: '查询指定加密货币的实时价格，免费无需 Key（公共接口有频率限制），支持 CORS',
    params: [
      {
        name: 'ids',
        type: 'string',
        defaultValue: 'bitcoin,ethereum',
        required: true,
        description: '币种 id，逗号分隔，如 bitcoin,ethereum,solana',
      },
      {
        name: 'vs',
        type: 'string',
        defaultValue: 'usd,cny',
        required: false,
        description: '计价货币，逗号分隔，如 usd,cny,eur',
      },
    ],
    pinned: false,
  },
  {
    id: 91,
    name: 'CoinPaprika 币种行情',
    url: 'https://api.coinpaprika.com/v1/tickers/{coinId}',
    method: 'GET',
    category: '金融',
    description: '查询单个加密货币的实时行情、市值与流通量，免费无 Key，支持 CORS',
    params: [
      {
        name: 'coinId',
        type: 'string',
        defaultValue: 'btc-bitcoin',
        required: true,
        description: '币种 id，如 btc-bitcoin、eth-ethereum',
      },
    ],
    pinned: false,
  },
  {
    id: 92,
    name: 'CoinPaprika 全球市场',
    url: 'https://api.coinpaprika.com/v1/global',
    method: 'GET',
    category: '金融',
    description: '全球加密货币市场总市值、24h 成交量与 BTC 占比，免费无 Key，支持 CORS',
    params: [],
    pinned: false,
  },
  {
    id: 93,
    name: 'Kraken 行情',
    url: 'https://api.kraken.com/0/public/Ticker?pair={pair}',
    method: 'GET',
    category: '金融',
    description: '查询 Kraken 交易所指定交易对的实时买/卖价、成交量与最新成交价，支持 CORS',
    params: [
      {
        name: 'pair',
        type: 'string',
        defaultValue: 'XBTUSD',
        required: true,
        description: '交易对，如 XBTUSD、ETHUSD、XBT EUR',
      },
    ],
    pinned: false,
  },
  {
    id: 94,
    name: 'Blockchain.info BTC 汇率',
    url: 'https://blockchain.info/ticker',
    method: 'GET',
    category: '金融',
    description: '比特币对各法币的实时汇率（含 15 分钟价与最新价），免费无 Key，支持 CORS',
    params: [],
    pinned: false,
  },
  {
    id: 95,
    name: 'Frankfurter ECB 汇率',
    url: 'https://api.frankfurter.dev/v1/latest?base={base}&symbols={symbols}',
    method: 'GET',
    category: '金融',
    description: '欧洲央行（ECB）每日参考汇率，免费无 Key，支持 CORS',
    params: [
      {
        name: 'base',
        type: 'string',
        defaultValue: 'USD',
        required: false,
        description: '基准货币，如 USD、EUR',
      },
      {
        name: 'symbols',
        type: 'string',
        defaultValue: 'CNY,EUR',
        required: false,
        description: '目标货币，逗号分隔，如 CNY,EUR,GBP',
      },
    ],
    pinned: false,
  },
  {
    id: 96,
    name: 'NBP 波兰央行汇率',
    url: 'https://api.nbp.pl/api/exchangerates/rates/{table}/{code}/?format=json',
    method: 'GET',
    category: '金融',
    description: '波兰国家银行（NBP）发布的官方汇率，免费无 Key，支持 CORS',
    params: [
      {
        name: 'table',
        type: 'string',
        defaultValue: 'A',
        required: false,
        description: '汇率表：A（主要货币）、B（次要货币）、C（非交割远期）',
      },
      {
        name: 'code',
        type: 'string',
        defaultValue: 'USD',
        required: true,
        description: '货币代码，如 USD、EUR、GBP',
      },
    ],
    pinned: false,
  },
  {
    id: 97,
    name: 'Gold-API 贵金属价格',
    url: 'https://api.gold-api.com/price/{symbol}',
    method: 'GET',
    category: '金融',
    description: '实时黄金/贵金属价格（美元/盎司），免费无 Key，支持 CORS',
    params: [
      {
        name: 'symbol',
        type: 'string',
        defaultValue: 'XAU',
        required: false,
        description: '金属代码：XAU=黄金，XAG=白银，XPT=铂金，XPD=钯金',
      },
    ],
    pinned: false,
  },
  {
    id: 98,
    name: '随机古诗词',
    url: 'https://poetry.palemoky.com/api/poems/random',
    method: 'GET',
    category: '中文',
    description:
      '诗泉随机古诗词接口，收录约37万首唐诗宋词元曲，返回标题、作者与正文数组，免费无需Key，支持CORS。',
    params: [],
    pinned: false,
  },
  {
    id: 99,
    name: '中文诗歌(唐诗)',
    url: 'https://api.timelessq.com/poetry?page={page}&pageSize={pageSize}',
    method: 'GET',
    category: '中文',
    description:
      'Timeless公共API·中文诗歌，随机/分页返回唐诗宋词（含作者、正文、标签），免费无需Key，支持CORS。',
    params: [
      {
        name: 'page',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '页码，每页10条',
      },
      {
        name: 'pageSize',
        type: 'number',
        defaultValue: '10',
        required: false,
        description: '每页条数',
      },
    ],
    pinned: false,
  },
  {
    id: 100,
    name: '成语查询',
    url: 'https://api.timelessq.com/idiom?wd={wd}&page={page}&pageSize={pageSize}',
    method: 'GET',
    category: '中文',
    description:
      'Timeless公共API·成语大全，3万+词库，返回拼音、释义、出处、近义词、反义词、例句等，免费无需Key，支持CORS。',
    params: [
      {
        name: 'wd',
        type: 'string',
        defaultValue: '一心一意',
        required: false,
        description: '要查询的成语关键词',
      },
      {
        name: 'page',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '页码',
      },
      {
        name: 'pageSize',
        type: 'number',
        defaultValue: '10',
        required: false,
        description: '每页条数',
      },
    ],
    pinned: false,
  },
  {
    id: 101,
    name: '毒鸡汤',
    url: 'https://api.oddfar.com/yl/q.php',
    method: 'GET',
    category: '中文',
    description:
      '奇远语录接口·毒鸡汤，句句“治愈”人心，免费无需Key，支持CORS。不传参数即返回毒鸡汤。',
    params: [
      {
        name: 'c',
        type: 'string',
        defaultValue: '1007',
        required: false,
        description: '句子类型，1007=毒鸡汤，1001=土味情话',
      },
      {
        name: 'encode',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '返回编码，留空=纯文本；填 json 返回 JSON',
      },
    ],
    pinned: false,
  },
  {
    id: 102,
    name: '早安心语',
    url: 'https://api.qqsuu.cn/api/dm-zaoan',
    method: 'GET',
    category: '中文',
    description: '趣API·每日早安心语，返回温馨正能量短句，免费无需Key，支持CORS。',
    params: [],
    pinned: false,
  },
  {
    id: 103,
    name: '晚安心语',
    url: 'https://api.qqsuu.cn/api/dm-wanan',
    method: 'GET',
    category: '中文',
    description: '趣API·每日晚安心语，返回暖心短句，免费无需Key，支持CORS。',
    params: [],
    pinned: false,
  },
  {
    id: 104,
    name: '舔狗日记',
    url: 'https://api.qqsuu.cn/api/dm-tiangou',
    method: 'GET',
    category: '中文',
    description: '趣API·舔狗日记，返回搞笑自嘲短句，免费无需Key，支持CORS。',
    params: [],
    pinned: false,
  },
  {
    id: 106,
    name: 'npm 包信息',
    url: 'https://registry.npmjs.org/{package}',
    method: 'GET',
    category: '开发',
    description: '获取 npm 包的完整元数据，包括版本、依赖、描述与维护者信息。',
    params: [
      {
        name: 'package',
        type: 'string',
        defaultValue: 'vue',
        required: true,
        description: 'npm 包名，例如 vue、react、express',
      },
    ],
    pinned: false,
  },
  {
    id: 107,
    name: 'npm 下载量',
    url: 'https://api.npmjs.org/downloads/point/{period}/{package}',
    method: 'GET',
    category: '开发',
    description: '获取 npm 包在指定时间段内的下载量统计数据。',
    params: [
      {
        name: 'period',
        type: 'string',
        defaultValue: 'last-week',
        required: true,
        description: '统计周期：last-day / last-week / last-month / last-year',
      },
      {
        name: 'package',
        type: 'string',
        defaultValue: 'vue',
        required: true,
        description: 'npm 包名',
      },
    ],
    pinned: false,
  },
  {
    id: 108,
    name: 'jsDelivr 包版本',
    url: 'https://data.jsdelivr.com/v1/package/npm/{name}',
    method: 'GET',
    category: '开发',
    description: '获取 npm 包在 jsDelivr CDN 上的全部版本、标签与发布时间信息。',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'vue',
        required: true,
        description: 'npm 包名',
      },
    ],
    pinned: false,
  },
  {
    id: 109,
    name: 'cdnjs 库信息',
    url: 'https://api.cdnjs.com/libraries/{name}',
    method: 'GET',
    category: '开发',
    description: '获取 cdnjs 上前端开源库的版本列表与文件资源信息。',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'vue',
        required: true,
        description: 'cdnjs 库名，例如 vue、jquery、lodash',
      },
    ],
    pinned: false,
  },
  {
    id: 110,
    name: 'GitHub 仓库信息',
    url: 'https://api.github.com/repos/{owner}/{repo}',
    method: 'GET',
    category: '开发',
    description: '获取指定 GitHub 仓库的详细信息，包括星标数、描述、主要语言等。',
    params: [
      {
        name: 'owner',
        type: 'string',
        defaultValue: 'vuejs',
        required: true,
        description: '仓库所有者（组织或用户名）',
      },
      {
        name: 'repo',
        type: 'string',
        defaultValue: 'core',
        required: true,
        description: '仓库名称',
      },
    ],
    pinned: false,
  },
  {
    id: 111,
    name: 'GitHub 仓库搜索',
    url: 'https://api.github.com/search/repositories?q={keyword}',
    method: 'GET',
    category: '开发',
    description: '按关键词搜索 GitHub 公开仓库，返回匹配结果与排序信息。',
    params: [
      {
        name: 'keyword',
        type: 'string',
        defaultValue: 'vue',
        required: true,
        description: '搜索关键词，可附加语言/星标等限定，如 vue+language:typescript',
      },
    ],
    pinned: false,
  },
  {
    id: 112,
    name: 'GitHub 状态页',
    url: 'https://www.githubstatus.com/api/v2/status.json',
    method: 'GET',
    category: '开发',
    description: '获取 GitHub 各项服务的实时运行状态、事件与历史可用性。',
    params: [],
    pinned: false,
  },
  {
    id: 113,
    name: 'shields 徽章',
    url: 'https://img.shields.io/badge/{label}-{message}-{color}',
    method: 'GET',
    category: '开发',
    description: '生成自定义静态 shields 徽章图片（SVG），常用于项目 README。',
    params: [
      {
        name: 'label',
        type: 'string',
        defaultValue: 'build',
        required: true,
        description: '徽章左侧标签文本',
      },
      {
        name: 'message',
        type: 'string',
        defaultValue: 'passing',
        required: true,
        description: '徽章右侧消息文本',
      },
      {
        name: 'color',
        type: 'string',
        defaultValue: 'brightgreen',
        required: false,
        description: '右侧颜色，如 brightgreen / blue / red / orange / lightgrey',
      },
    ],
    pinned: false,
  },
  {
    id: 114,
    name: 'Hacker News 热门',
    url: 'https://hacker-news.firebaseio.com/v0/topstories.json',
    method: 'GET',
    category: '开发',
    description: '获取 Hacker News 当前热门故事的 ID 列表，可配合 item 接口获取详情。',
    params: [],
    pinned: false,
  },
  {
    id: 115,
    name: 'Stack Exchange 站点信息',
    url: 'https://api.stackexchange.com/2.3/info?site={site}',
    method: 'GET',
    category: '开发',
    description: '获取指定 Stack Exchange 站点（如 Stack Overflow）的元信息与统计概况。',
    params: [
      {
        name: 'site',
        type: 'string',
        defaultValue: 'stackoverflow',
        required: true,
        description: '站点标识，如 stackoverflow / superuser / serverfault',
      },
    ],
    pinned: false,
  },
  {
    id: 116,
    name: 'JSONPlaceholder 用户',
    url: 'https://jsonplaceholder.typicode.com/users/{id}',
    method: 'GET',
    category: '开发',
    description: '获取 JSONPlaceholder 提供的模拟用户数据，适用于接口联调与前端测试。',
    params: [
      {
        name: 'id',
        type: 'string',
        defaultValue: '1',
        required: false,
        description: '用户 ID（1-10），留空则返回全部用户列表',
      },
    ],
    pinned: false,
  },
  {
    id: 122,
    name: '随机用户资料',
    url: 'https://randomuser.me/api/',
    method: 'GET',
    category: '图片',
    description: '返回随机用户资料（含头像 URL），可选 results/gender',
    params: [
      {
        name: 'results',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '返回用户数量',
      },
      {
        name: 'gender',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '性别筛选，male/female',
      },
    ],
    pinned: false,
  },
  {
    id: 145,
    name: '公网IP查询 (ipify)',
    url: 'https://api.ipify.org?format=json',
    method: 'GET',
    category: '地理',
    description: '获取当前设备的公网 IP 地址，无需 Key、支持 CORS',
    params: [
      {
        name: 'format',
        type: 'string',
        defaultValue: 'json',
        required: false,
        description: '返回格式，json 或 text',
      },
    ],
    pinned: false,
  },
  {
    id: 146,
    name: '天气预报 (Open-Meteo)',
    url: 'https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&current_weather=true',
    method: 'GET',
    category: '地理',
    description: '免 Key 的天气预报，支持当前、逐小时与逐日数据',
    params: [
      {
        name: 'latitude',
        type: 'number',
        defaultValue: '39.9042',
        required: true,
        description: '纬度，如北京 39.9042',
      },
      {
        name: 'longitude',
        type: 'number',
        defaultValue: '116.4074',
        required: true,
        description: '经度，如北京 116.4074',
      },
      {
        name: 'current_weather',
        type: 'string',
        defaultValue: 'true',
        required: false,
        description: '是否返回当前天气',
      },
    ],
    pinned: false,
  },
  {
    id: 147,
    name: '地理编码 (Open-Meteo)',
    url: 'https://geocoding-api.open-meteo.com/v1/search?name={name}&count=1',
    method: 'GET',
    category: '地理',
    description: '按城市/地名搜索并返回经纬度等地理编码结果',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'Beijing',
        required: true,
        description: '要搜索的地名或城市',
      },
      {
        name: 'count',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '返回结果数量',
      },
    ],
    pinned: false,
  },
  {
    id: 148,
    name: '太空新闻',
    url: 'https://api.spaceflightnewsapi.net/v4/articles/',
    method: 'GET',
    category: '数据',
    description: '获取最新太空与航天新闻文章（标题、摘要、来源、图片）',
    params: [
      {
        name: 'search',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '关键词搜索，留空返回最新文章列表',
      },
      {
        name: 'limit',
        type: 'number',
        defaultValue: '10',
        required: false,
        description: '返回文章数量上限',
      },
    ],
    pinned: false,
  },
  {
    id: 149,
    name: '火箭发射计划',
    url: 'https://ll.thespacedevs.com/2.2.0/launch/upcoming/',
    method: 'GET',
    category: '数据',
    description: '获取即将进行的全球火箭发射计划（时间、火箭、发射台）',
    params: [
      {
        name: 'limit',
        type: 'number',
        defaultValue: '5',
        required: false,
        description: '返回发射条目数量上限',
      },
    ],
    pinned: false,
  },
  {
    id: 150,
    name: '中文诗歌(唐诗)',
    url: 'https://api.timelessq.com/poetry',
    method: 'GET',
    category: '中文',
    description:
      'Timeless公共API·中文诗歌，随机/分页返回唐诗宋词（含作者、正文、标签），免费无需Key，支持CORS。',
    params: [
      {
        name: 'page',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '页码，每页10条',
      },
      {
        name: 'pageSize',
        type: 'number',
        defaultValue: '10',
        required: false,
        description: '每页条数',
      },
    ],
    pinned: false,
  },
  {
    id: 151,
    name: '成语查询',
    url: 'https://api.timelessq.com/idiom',
    method: 'GET',
    category: '中文',
    description:
      'Timeless公共API·成语大全，3万+词库，返回拼音、释义、出处、近义词、反义词、例句等，免费无需Key，支持CORS。',
    params: [
      {
        name: 'wd',
        type: 'string',
        defaultValue: '一心一意',
        required: false,
        description: '要查询的成语关键词',
      },
      {
        name: 'page',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '页码',
      },
      {
        name: 'pageSize',
        type: 'number',
        defaultValue: '10',
        required: false,
        description: '每页条数',
      },
    ],
    pinned: false,
  },
  {
    id: 152,
    name: 'MyMemory 机器翻译',
    url: 'https://api.mymemory.translated.net/get',
    method: 'GET',
    category: 'AI',
    description: '免费、免 Key、支持 CORS 的多语种机器翻译接口(每日约 5000 词免费额度)。',
    params: [
      {
        name: 'q',
        type: 'string',
        defaultValue: '',
        required: true,
        description: '待翻译文本',
      },
      {
        name: 'langpair',
        type: 'string',
        defaultValue: 'zh-CN|en',
        required: true,
        description: '语言对,格式如 en|zh-CN 或 zh-CN|en',
      },
    ],
    pinned: false,
  },
  {
    id: 153,
    name: 'Lingva 翻译',
    url: 'https://lingva.ml/api/v1/{source}/{target}/{query}',
    method: 'GET',
    category: 'AI',
    description:
      '免费、免 Key、支持 CORS 的翻译接口(基于 Google 翻译的开源前端),source 可填 auto 自动检测语言。',
    params: [
      {
        name: 'source',
        type: 'string',
        defaultValue: 'auto',
        required: true,
        description: '源语言代码,如 auto / en / zh-CN',
      },
      {
        name: 'target',
        type: 'string',
        defaultValue: 'zh-CN',
        required: true,
        description: '目标语言代码,如 zh-CN / en',
      },
      {
        name: 'query',
        type: 'string',
        defaultValue: '',
        required: true,
        description: '待翻译文本',
      },
    ],
    pinned: false,
  },
  {
    id: 154,
    name: 'LanguageTool 语法检查',
    url: 'https://api.languagetool.org/v2/check',
    method: 'GET',
    category: 'AI',
    description:
      '免费、免 Key、支持 CORS 的多语种语法/拼写/错别字检查接口(中文需付费版,免费版支持英文等)。',
    params: [
      {
        name: 'text',
        type: 'string',
        defaultValue: '',
        required: true,
        description: '待检查的文本',
      },
      {
        name: 'language',
        type: 'string',
        defaultValue: 'auto',
        required: false,
        description: '语言代码,如 en-US / auto',
      },
    ],
    pinned: false,
  },
  {
    id: 155,
    name: 'Free Dictionary 词典',
    url: 'https://api.dictionaryapi.dev/api/v2/entries/{lang}/{word}',
    method: 'GET',
    category: 'AI',
    description: '免费、免 Key、支持 CORS 的英文词典释义/音标/例句查询接口。',
    params: [
      {
        name: 'lang',
        type: 'string',
        defaultValue: 'en',
        required: true,
        description: '词典语言,如 en',
      },
      {
        name: 'word',
        type: 'string',
        defaultValue: '',
        required: true,
        description: '查询的单词',
      },
    ],
    pinned: false,
  },
  {
    id: 156,
    name: 'Datamuse 语义相关词',
    url: 'https://api.datamuse.com/words',
    method: 'GET',
    category: 'AI',
    description: '免费、免 Key、支持 CORS 的英语词语关系/语义相似度查询(近义、押韵等)。',
    params: [
      {
        name: 'ml',
        type: 'string',
        defaultValue: '',
        required: true,
        description: '语义相近的词(means-like),如 apple',
      },
      {
        name: 'max',
        type: 'number',
        defaultValue: '10',
        required: false,
        description: '返回结果数量上限',
      },
    ],
    pinned: false,
  },
  {
    id: 157,
    name: 'Datamuse 词语补全',
    url: 'https://api.datamuse.com/sug',
    method: 'GET',
    category: 'AI',
    description: '免费、免 Key、支持 CORS 的英语前缀联想/自动补全接口。',
    params: [
      {
        name: 's',
        type: 'string',
        defaultValue: '',
        required: true,
        description: '前缀片段,如 hel',
      },
    ],
    pinned: false,
  },
  {
    id: 159,
    name: 'Wikipedia 全文搜索',
    url: 'https://en.wikipedia.org/w/api.php',
    method: 'GET',
    category: 'AI',
    description:
      '免费、免 Key、支持 CORS 的维基百科全文检索接口(维基 API 需带 origin=* 才返回 CORS 头)。',
    params: [
      {
        name: 'action',
        type: 'string',
        defaultValue: 'query',
        required: false,
        description: '固定值 query',
      },
      {
        name: 'list',
        type: 'string',
        defaultValue: 'search',
        required: false,
        description: '固定值 search',
      },
      {
        name: 'srsearch',
        type: 'string',
        defaultValue: '',
        required: true,
        description: '搜索关键词',
      },
      {
        name: 'format',
        type: 'string',
        defaultValue: 'json',
        required: false,
        description: '固定值 json',
      },
      {
        name: 'origin',
        type: 'string',
        defaultValue: '*',
        required: false,
        description: 'CORS 必需,固定值 *',
      },
    ],
    pinned: false,
  },
  {
    id: 160,
    name: 'Wikidata 实体搜索',
    url: 'https://www.wikidata.org/w/api.php',
    method: 'GET',
    category: 'AI',
    description: '免费、免 Key、支持 CORS 的知识图谱实体搜索接口(需带 origin=* 才返回 CORS 头)。',
    params: [
      {
        name: 'action',
        type: 'string',
        defaultValue: 'wbsearchentities',
        required: false,
        description: '固定值 wbsearchentities',
      },
      {
        name: 'search',
        type: 'string',
        defaultValue: '',
        required: true,
        description: '实体关键词',
      },
      {
        name: 'language',
        type: 'string',
        defaultValue: 'en',
        required: false,
        description: '返回语言代码',
      },
      {
        name: 'format',
        type: 'string',
        defaultValue: 'json',
        required: false,
        description: '固定值 json',
      },
      {
        name: 'origin',
        type: 'string',
        defaultValue: '*',
        required: false,
        description: 'CORS 必需,固定值 *',
      },
    ],
    pinned: false,
  },
  {
    id: 162,
    name: 'Crossref 学术文献',
    url: 'https://api.crossref.org/works',
    method: 'GET',
    category: 'AI',
    description: '免费、免 Key、支持 CORS 的学术文献元数据检索接口(论文/期刊 DOI 信息)。',
    params: [
      {
        name: 'query',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '检索关键词',
      },
      {
        name: 'rows',
        type: 'number',
        defaultValue: '10',
        required: false,
        description: '返回条数',
      },
    ],
    pinned: false,
  },
  {
    id: 163,
    name: '占位图生成 placehold.co',
    url: 'https://placehold.co/{size}',
    method: 'GET',
    category: '前端',
    description: '免费、免 Key、支持 CORS 的占位图生成服务,可指定尺寸与文案',
    params: [
      {
        name: 'size',
        type: 'string',
        defaultValue: '600x400',
        required: true,
        description: '图片尺寸,格式为 宽x高,如 600x400',
      },
    ],
    pinned: false,
  },
  {
    id: 164,
    name: '二维码生成 QR Server',
    url: 'https://api.qrserver.com/v1/create-qr-code/',
    method: 'GET',
    category: '前端',
    description: '免费、免 Key、支持 CORS 的二维码图片生成接口',
    params: [
      {
        name: 'data',
        type: 'string',
        defaultValue: 'https://example.com',
        required: true,
        description: '要编码为二维码的文本或网址',
      },
      {
        name: 'size',
        type: 'string',
        defaultValue: '150x150',
        required: false,
        description: '二维码尺寸,格式 宽x高',
      },
    ],
    pinned: false,
  },
  {
    id: 165,
    name: 'SVG 头像生成 DiceBear',
    url: 'https://api.dicebear.com/7.x/{style}/svg',
    method: 'GET',
    category: '前端',
    description: '免费、免 Key、支持 CORS 的可定制 SVG 卡通头像生成服务',
    params: [
      {
        name: 'style',
        type: 'string',
        defaultValue: 'avataaars',
        required: true,
        description: '头像风格,如 avataaars、bottts、identicon',
      },
      {
        name: 'seed',
        type: 'string',
        defaultValue: 'user',
        required: false,
        description: '随机种子,相同 seed 生成相同头像',
      },
    ],
    pinned: false,
  },
  {
    id: 166,
    name: '首字母头像 UI Avatars',
    url: 'https://ui-avatars.com/api/',
    method: 'GET',
    category: '前端',
    description: '免费、免 Key、支持 CORS 的根据姓名生成首字母头像的服务',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'John Doe',
        required: true,
        description: '用于生成首字母的姓名',
      },
    ],
    pinned: false,
  },
  {
    id: 167,
    name: '机器人头像 RoboHash',
    url: 'https://robohash.org/{text}',
    method: 'GET',
    category: '前端',
    description: '免费、免 Key、支持 CORS 的根据文本生成机器人/怪物头像的服务',
    params: [
      {
        name: 'text',
        type: 'string',
        defaultValue: 'robot',
        required: true,
        description: '任意字符串,作为头像生成种子',
      },
    ],
    pinned: false,
  },
  {
    id: 168,
    name: '网站 Favicon 获取 Favicone',
    url: 'https://favicone.com/{domain}',
    method: 'GET',
    category: '前端',
    description: '免费、免 Key、支持 CORS 的按域名获取网站 favicon 图标服务',
    params: [
      {
        name: 'domain',
        type: 'string',
        defaultValue: 'github.com',
        required: true,
        description: '目标网站域名,如 github.com',
      },
    ],
    pinned: false,
  },
  {
    id: 169,
    name: '短链接生成 is.gd',
    url: 'https://is.gd/create.php',
    method: 'GET',
    category: '前端',
    description: '免费、免 Key、支持 CORS 的短链接生成接口,返回 JSON',
    params: [
      {
        name: 'url',
        type: 'string',
        defaultValue: 'https://example.com',
        required: true,
        description: '要缩短的原始网址',
      },
      {
        name: 'format',
        type: 'string',
        defaultValue: 'json',
        required: false,
        description: '返回格式,json 或 simple',
      },
    ],
    pinned: false,
  },
  {
    id: 170,
    name: '假数据商店 DummyJSON',
    url: 'https://dummyjson.com/products/{id}',
    method: 'GET',
    category: '前端',
    description: '免费、免 Key、支持 CORS 的假数据服务,提供商品等结构化数据',
    params: [
      {
        name: 'id',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '商品 ID,不填时返回列表',
      },
    ],
    pinned: false,
  },
  {
    id: 171,
    name: '获取公网 IP ipify',
    url: 'https://api.ipify.org',
    method: 'GET',
    category: '前端',
    description: '免费、免 Key、支持 CORS 的获取当前访问者公网 IP 地址的接口',
    params: [
      {
        name: 'format',
        type: 'string',
        defaultValue: 'json',
        required: false,
        description: '返回格式,json 或 text',
      },
    ],
    pinned: false,
  },
  {
    id: 172,
    name: 'IP 地理定位',
    url: 'https://ipwho.is/',
    method: 'GET',
    category: '后端',
    description: '免费免Key、支持CORS;返回调用方IP的国家/城市/经纬度/时区/运营商等地理信息。',
    params: [],
    pinned: false,
  },
  {
    id: 173,
    name: 'User-Agent 解析',
    url: 'https://httpbin.org/user-agent',
    method: 'GET',
    category: '后端',
    description: '免费免Key、支持CORS;回显请求携带的 User-Agent 字符串,便于服务端UA逻辑联调。',
    params: [],
    pinned: false,
  },
  {
    id: 174,
    name: 'UUID 生成',
    url: 'https://httpbin.org/uuid',
    method: 'GET',
    category: '后端',
    description: '免费免Key、支持CORS;生成并返回一个随机 UUID,常用于后端生成唯一ID。',
    params: [],
    pinned: false,
  },
  {
    id: 175,
    name: '版本化 UUID 生成',
    url: 'https://www.uuidtools.com/api/generate/{version}',
    method: 'GET',
    category: '后端',
    description: '免费免Key、支持CORS;按指定版本(v1/v4)批量生成 UUID。',
    params: [
      {
        name: 'version',
        type: 'string',
        defaultValue: 'v4',
        required: false,
        description: 'UUID 版本,可选 v1 或 v4,默认 v4。',
      },
    ],
    pinned: false,
  },
  {
    id: 176,
    name: 'HTTP 请求头获取',
    url: 'https://httpbin.org/headers',
    method: 'GET',
    category: '后端',
    description: '免费免Key、支持CORS;回显本次请求的全部 HTTP 头,便于排查鉴权/代理头传递。',
    params: [],
    pinned: false,
  },
  {
    id: 177,
    name: 'DNS over HTTPS 查询',
    url: 'https://dns.google/resolve',
    method: 'GET',
    category: '后端',
    description: '免费免Key、支持CORS;通过 Google 公共 DNS 解析域名记录(A/AAAA/MX/TXT/NS 等)。',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: '',
        required: true,
        description: '要解析的域名,例如 example.com。',
      },
      {
        name: 'type',
        type: 'string',
        defaultValue: 'A',
        required: false,
        description: 'DNS 记录类型,可选 A/AAAA/MX/TXT/NS,默认 A。',
      },
    ],
    pinned: false,
  },
  {
    id: 178,
    name: '时区当前时间',
    url: 'https://www.timeapi.io/api/Time/current/zone',
    method: 'GET',
    category: '后端',
    description: '免费免Key、支持CORS;根据 IANA 时区返回该时区当前日期时间,便于时区转换。',
    params: [
      {
        name: 'timeZone',
        type: 'string',
        defaultValue: 'Asia/Shanghai',
        required: false,
        description: 'IANA 时区名称,例如 Asia/Shanghai、Europe/London。',
      },
    ],
    pinned: false,
  },
  {
    id: 179,
    name: 'ISBN 图书查询',
    url: 'https://openlibrary.org/isbn/{isbn}.json',
    method: 'GET',
    category: '后端',
    description: '免费免Key、支持CORS;根据 ISBN 查询图书元数据(标题/作者/出版信息)。',
    params: [
      {
        name: 'isbn',
        type: 'string',
        defaultValue: '',
        required: true,
        description: 'ISBN 号码,例如 9780140328721。',
      },
    ],
    pinned: false,
  },
  {
    id: 180,
    name: '请求回显调试',
    url: 'https://httpbin.org/get',
    method: 'GET',
    category: '后端',
    description: '免费免Key、支持CORS;回显本次请求的 URL、请求头与来源IP,QA联调与网关排查必备。',
    params: [],
    pinned: false,
  },
  {
    id: 181,
    name: 'HttpBin 状态码',
    url: 'https://httpbin.org/status/{code}',
    method: 'GET',
    category: '测试',
    description:
      '免费免Key、支持CORS;按路径参数返回指定HTTP状态码(如200/404/500),用于测试前端错误处理分支。',
    params: [
      {
        name: 'code',
        type: 'number',
        defaultValue: '200',
        required: true,
        description: '需要返回的HTTP状态码,例如200、401、500。',
      },
    ],
    pinned: false,
  },
  {
    id: 182,
    name: 'HttpBin 通用Mock',
    url: 'https://httpbin.org/anything/{path}',
    method: 'GET',
    category: '测试',
    description: '免费免Key、支持CORS;万能mock接口,回显任意路径与请求体,适合快速搭建测试桩。',
    params: [
      {
        name: 'path',
        type: 'string',
        defaultValue: 'test',
        required: false,
        description: '任意路径片段,用于区分不同mock场景,留空默认test。',
      },
    ],
    pinned: false,
  },
  {
    id: 183,
    name: 'JSONPlaceholder 用户列表',
    url: 'https://jsonplaceholder.typicode.com/users',
    method: 'GET',
    category: '测试',
    description: '免费免Key、支持CORS;返回10条标准REST风格的假用户数据,常用于前端列表与CRUD联调。',
    params: [],
    pinned: false,
  },
  {
    id: 184,
    name: 'JSONPlaceholder 文章详情',
    url: 'https://jsonplaceholder.typicode.com/posts/{id}',
    method: 'GET',
    category: '测试',
    description: '免费免Key、支持CORS;按路径参数id返回单篇文章,演示含路径参数的接口调用。',
    params: [
      {
        name: 'id',
        type: 'number',
        defaultValue: '1',
        required: true,
        description: '文章ID,例如1、2、3。',
      },
    ],
    pinned: false,
  },
  {
    id: 186,
    name: 'DummyJSON 商品列表',
    url: 'https://dummyjson.com/products',
    method: 'GET',
    category: '测试',
    description: '免费免Key、支持CORS;返回结构化假商品数据(标题/价格/库存),适合电商类页面联调。',
    params: [
      {
        name: 'limit',
        type: 'number',
        defaultValue: '',
        required: false,
        description: '返回条数上限,留空默认30。',
      },
      {
        name: 'skip',
        type: 'number',
        defaultValue: '',
        required: false,
        description: '跳过条数,用于分页,留空默认0。',
      },
    ],
    pinned: false,
  },
  {
    id: 187,
    name: 'DummyJSON 健康测试',
    url: 'https://dummyjson.com/test',
    method: 'GET',
    category: '测试',
    description: '免费免Key、支持CORS;返回固定 {"test":"ok"} 响应,适合做接口连通性与健康检测。',
    params: [],
    pinned: false,
  },
  {
    id: 188,
    name: 'Agify 名字推年龄',
    url: 'https://api.agify.io',
    method: 'GET',
    category: '测试',
    description: '免费免Key、支持CORS;根据姓名预测年龄,常用于随机数据/演示展示。',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: '',
        required: true,
        description: '待预测的名字,例如 michael。',
      },
    ],
    pinned: false,
  },
  {
    id: 189,
    name: 'Genderize 名字推性别',
    url: 'https://api.genderize.io',
    method: 'GET',
    category: '测试',
    description: '免费免Key、支持CORS;根据姓名预测性别,常用于随机数据/演示展示。',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: '',
        required: true,
        description: '待预测的名字,例如 jessica。',
      },
    ],
    pinned: false,
  },
  {
    id: 190,
    name: 'Nationalize 名字推国籍',
    url: 'https://api.nationalize.io',
    method: 'GET',
    category: '测试',
    description: '免费免Key、支持CORS;根据姓名预测最可能国籍,常用于随机数据/演示展示。',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: '',
        required: true,
        description: '待预测的名字,例如 lucas。',
      },
    ],
    pinned: false,
  },
  {
    id: 191,
    name: '二维码生成(QuickChart)',
    url: 'https://quickchart.io/qr',
    method: 'GET',
    category: '产品',
    description: '生成二维码图片,免费、免 Key、支持 CORS,可控制尺寸与边距',
    params: [
      {
        name: 'text',
        type: 'string',
        defaultValue: 'hello',
        required: true,
        description: '要编码为二维码的文本或网址',
      },
      {
        name: 'size',
        type: 'number',
        defaultValue: '200',
        required: false,
        description: '图片像素尺寸,如 300',
      },
      {
        name: 'margin',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '二维码四周留白边距',
      },
    ],
    pinned: false,
  },
  {
    id: 192,
    name: '网页链接预览(Microlink)',
    url: 'https://api.microlink.io/',
    method: 'GET',
    category: '产品',
    description: '抓取网页标题/描述/OG 图/截图等元数据,免费、免 Key、支持 CORS',
    params: [
      {
        name: 'url',
        type: 'string',
        defaultValue: 'https://example.com',
        required: true,
        description: '目标网页地址',
      },
      {
        name: 'screenshot',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '设为 true 额外返回网站截图图片地址',
      },
      {
        name: 'palette',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '设为 true 额外返回网站主题色板',
      },
    ],
    pinned: false,
  },
  {
    id: 193,
    name: '网页截图(Thum.io)',
    url: 'https://image.thum.io/get/{target}',
    method: 'GET',
    category: '产品',
    description: '根据网址直接返回网站截图图片,免费、免 Key、支持 CORS',
    params: [
      {
        name: 'target',
        type: 'string',
        defaultValue: 'https://example.com',
        required: true,
        description: '目标网页完整地址(含 http/https)',
      },
      {
        name: 'width',
        type: 'number',
        defaultValue: '',
        required: false,
        description: '视口宽度像素,留空用默认',
      },
      {
        name: 'fullPage',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '设为 true 截取整页长图',
      },
    ],
    pinned: false,
  },
  {
    id: 194,
    name: '颜色查询(Color API)',
    url: 'https://www.thecolorapi.com/id',
    method: 'GET',
    category: '产品',
    description: '根据颜色值返回名称/HEX/RGB/HSL,免费、免 Key、支持 CORS',
    params: [
      {
        name: 'hex',
        type: 'string',
        defaultValue: '4411ee',
        required: true,
        description: '十六进制颜色值(不带 #)',
      },
    ],
    pinned: false,
  },
  {
    id: 195,
    name: '配色方案(Color API)',
    url: 'https://www.thecolorapi.com/scheme',
    method: 'GET',
    category: '产品',
    description: '基于一个颜色生成整套配色方案,免费、免 Key、支持 CORS',
    params: [
      {
        name: 'hex',
        type: 'string',
        defaultValue: '4411ee',
        required: true,
        description: '基准色十六进制(不带 #)',
      },
      {
        name: 'mode',
        type: 'string',
        defaultValue: 'analogic',
        required: false,
        description: '配色模式,如 analogic/monochrome/triad/complement',
      },
      {
        name: 'count',
        type: 'number',
        defaultValue: '5',
        required: false,
        description: '返回颜色数量',
      },
    ],
    pinned: false,
  },
  {
    id: 196,
    name: '自定义占位图(DummyImage)',
    url: 'https://dummyimage.com/{size}',
    method: 'GET',
    category: '产品',
    description: '生成可指定背景/文字色的占位图,免费、免 Key、支持 CORS',
    params: [
      {
        name: 'size',
        type: 'string',
        defaultValue: '600x400',
        required: true,
        description: '图片尺寸,格式 宽x高',
      },
      {
        name: 'bg',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '背景色,十六进制不带 #',
      },
      {
        name: 'textcolor',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '文字颜色,十六进制不带 #',
      },
      {
        name: 'text',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '图片上显示的文字',
      },
    ],
    pinned: false,
  },
  {
    id: 197,
    name: 'SVG 图标(Iconify)',
    url: 'https://api.iconify.design/{prefix}/{name}.svg',
    method: 'GET',
    category: '产品',
    description: '按图标集与名称返回 SVG 图标,免费、免 Key、支持 CORS,含数万图标',
    params: [
      {
        name: 'prefix',
        type: 'string',
        defaultValue: 'mdi',
        required: true,
        description: '图标集名称,如 mdi、lucide、fluent-emoji',
      },
      {
        name: 'name',
        type: 'string',
        defaultValue: 'home',
        required: true,
        description: '图标名称,如 home、heart、settings',
      },
    ],
    pinned: false,
  },
  {
    id: 198,
    name: '卡通头像(DiceBear)',
    url: 'https://api.dicebear.com/9.x/{style}/svg',
    method: 'GET',
    category: '产品',
    description: '生成卡通风格占位头像 SVG,免费、免 Key、支持 CORS,适合产品原型',
    params: [
      {
        name: 'style',
        type: 'string',
        defaultValue: 'adventurer',
        required: true,
        description: '头像风格,如 adventurer、bottts、thumbs、initials',
      },
      {
        name: 'seed',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '种子值,决定生成的具体头像(留空随机)',
      },
    ],
    pinned: false,
  },
  {
    id: 199,
    name: 'Google Fonts 字体CSS',
    url: 'https://fonts.googleapis.com/css2',
    method: 'GET',
    category: 'UI',
    description: '免费免Key支持CORS,获取指定字体的 @font-face CSS(返回CSS文本,可直接引入)',
    params: [
      {
        name: 'family',
        type: 'string',
        defaultValue: 'Roboto',
        required: true,
        description: '字体族名,空格用 + 连接,可带字重如 Roboto:wght@400;700',
      },
    ],
    pinned: false,
  },
  {
    id: 200,
    name: 'Iconify 图标集列表',
    url: 'https://api.iconify.design/collection',
    method: 'GET',
    category: 'UI',
    description: '免费免Key支持CORS,获取某图标集的元数据与全部可用图标名称列表',
    params: [
      {
        name: 'prefix',
        type: 'string',
        defaultValue: 'mdi',
        required: true,
        description: '图标集前缀,如 mdi、fa、carbon',
      },
    ],
    pinned: false,
  },
  {
    id: 201,
    name: 'Bacon Ipsum 占位文本',
    url: 'https://baconipsum.com/api/',
    method: 'GET',
    category: 'UI',
    description: '免费免Key支持CORS,生成英文 Lorem 风格占位文本,支持段落与句子控制',
    params: [
      {
        name: 'type',
        type: 'string',
        defaultValue: 'all-meat',
        required: false,
        description: '文本类型:all-meat(纯肉)或 meat-and-filler(混合)',
      },
      {
        name: 'sentences',
        type: 'number',
        defaultValue: '3',
        required: false,
        description: '句子数量',
      },
      {
        name: 'paras',
        type: 'number',
        defaultValue: '',
        required: false,
        description: '段落数量,留空则按 sentences 生成',
      },
      {
        name: 'start-with-lorem',
        type: 'string',
        defaultValue: '1',
        required: false,
        description: '是否以 Lorem 开头:1 是 / 0 否',
      },
    ],
    pinned: false,
  },
  {
    id: 202,
    name: 'Placehold.co 占位图',
    url: 'https://placehold.co/{width}x{height}',
    method: 'GET',
    category: 'UI',
    description: '免费免Key支持CORS,生成带自定义文字与配色的占位图,适合界面原型',
    params: [
      {
        name: 'width',
        type: 'number',
        defaultValue: '600',
        required: true,
        description: '图片宽度(像素)',
      },
      {
        name: 'height',
        type: 'number',
        defaultValue: '400',
        required: true,
        description: '图片高度(像素)',
      },
      {
        name: 'text',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '图上显示的文字',
      },
      {
        name: 'bg',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '背景色,十六进制,不含 #',
      },
      {
        name: 'color',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '文字颜色,十六进制,不含 #',
      },
    ],
    pinned: false,
  },
  {
    id: 204,
    name: 'DummyImage 占位图',
    url: 'https://dummyimage.com/{width}x{height}/{bg}/{fg}',
    method: 'GET',
    category: '资源',
    description: '免费、免 key 的自定义占位图生成,支持 CORS,可指定尺寸与颜色',
    params: [
      {
        name: 'width',
        type: 'number',
        defaultValue: '600',
        required: true,
        description: '图片宽度',
      },
      {
        name: 'height',
        type: 'number',
        defaultValue: '400',
        required: true,
        description: '图片高度',
      },
      {
        name: 'bg',
        type: 'string',
        defaultValue: '000',
        required: false,
        description: '背景色(十六进制,不含 #)',
      },
      {
        name: 'fg',
        type: 'string',
        defaultValue: 'fff',
        required: false,
        description: '前景文字颜色(十六进制,不含 #)',
      },
    ],
    pinned: false,
  },
  {
    id: 205,
    name: 'Placehold.co 占位图',
    url: 'https://placehold.co/{size}/{bg}/{fg}',
    method: 'GET',
    category: '资源',
    description: '免费、免 key 的占位图服务,支持 CORS,可自定义尺寸和文字颜色',
    params: [
      {
        name: 'size',
        type: 'string',
        defaultValue: '600x400',
        required: true,
        description: '尺寸,格式为 宽x高,如 600x400',
      },
      {
        name: 'bg',
        type: 'string',
        defaultValue: '000000',
        required: false,
        description: '背景色(十六进制)',
      },
      {
        name: 'fg',
        type: 'string',
        defaultValue: 'FFFFFF',
        required: false,
        description: '文字颜色(十六进制)',
      },
    ],
    pinned: false,
  },
  {
    id: 206,
    name: 'Simple Icons 品牌图标',
    url: 'https://cdn.simpleicons.org/{slug}/{color}',
    method: 'GET',
    category: '资源',
    description: '免费、免 key 的海量品牌 SVG 图标,支持 CORS,可用作前端图标直链',
    params: [
      {
        name: 'slug',
        type: 'string',
        defaultValue: 'github',
        required: true,
        description: '品牌 slug,详见 simpleicons.org 图标列表',
      },
      {
        name: 'color',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '图标颜色(十六进制,如 0000ff),留空为品牌原色',
      },
    ],
    pinned: false,
  },
  {
    id: 207,
    name: 'FlagCDN 国旗图标',
    url: 'https://flagcdn.com/{size}/{code}.png',
    method: 'GET',
    category: '资源',
    description: '免费、免 key 的国家国旗 PNG 图标,支持 CORS,可按国家代码获取',
    params: [
      {
        name: 'size',
        type: 'string',
        defaultValue: '80x60',
        required: false,
        description: '尺寸,如 80x60 / 160x120 / w1280',
      },
      {
        name: 'code',
        type: 'string',
        defaultValue: 'fr',
        required: true,
        description: '国家代码(小写 ISO),如 cn / us / fr',
      },
    ],
    pinned: false,
  },
  {
    id: 208,
    name: 'YesNo.wtf 问答 GIF',
    url: 'https://yesno.wtf/api',
    method: 'GET',
    category: '资源',
    description: '免费、免 key 的 yes/no 随机 GIF 接口,支持 CORS,返回动图直链',
    params: [],
    pinned: false,
  },
  {
    id: 209,
    name: 'OpenMoji 表情贴纸',
    url: 'https://cdn.jsdelivr.net/npm/openmoji@15.1.0/color/svg/{hex}.svg',
    method: 'GET',
    category: '资源',
    description: '免费、免 key 的开放表情贴纸 SVG(经 jsDelivr CDN),支持 CORS,可直链使用',
    params: [
      {
        name: 'hex',
        type: 'string',
        defaultValue: '1F600',
        required: true,
        description: 'emoji 的 Unicode 十六进制码点,如 1F600(笑脸)、2764(红心)',
      },
    ],
    pinned: false,
  },
  {
    id: 210,
    name: 'Lorem Picsum 图片列表',
    url: 'https://picsum.photos/v2/list',
    method: 'GET',
    category: '资源',
    description: '免费、免 key 的图库元数据列表,支持 CORS,返回作者与图片直链信息',
    params: [
      {
        name: 'page',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '页码',
      },
      {
        name: 'limit',
        type: 'number',
        defaultValue: '30',
        required: false,
        description: '每页返回数量',
      },
    ],
    pinned: false,
  },
  {
    id: 211,
    name: '当前时间(按时区)',
    url: 'https://www.timeapi.io/api/time/current/zone',
    method: 'GET',
    category: '工具',
    description: '免费、免Key、支持CORS，获取指定IANA时区的当前日期时间',
    params: [
      {
        name: 'timeZone',
        type: 'string',
        defaultValue: 'Asia/Shanghai',
        required: true,
        description: 'IANA时区名，如 Asia/Shanghai、Europe/London',
      },
    ],
    pinned: false,
  },
  {
    id: 212,
    name: 'UUID生成',
    url: 'https://www.uuidtools.com/api/generate/v4',
    method: 'GET',
    category: '工具',
    description: '免费、免Key、支持CORS，生成随机UUID v4字符串(返回字符串数组)',
    params: [],
    pinned: false,
  },
  {
    id: 213,
    name: '网络延迟测试',
    url: 'https://httpbin.org/delay/{seconds}',
    method: 'GET',
    category: '工具',
    description: '免费、免Key、支持CORS，延迟指定秒数后响应，用于超时与加载态测试',
    params: [
      {
        name: 'seconds',
        type: 'number',
        defaultValue: '3',
        required: true,
        description: '延迟秒数(0-10)',
      },
    ],
    pinned: false,
  },
  {
    id: 214,
    name: 'Base64解码',
    url: 'https://httpbin.org/base64/{value}',
    method: 'GET',
    category: '工具',
    description: '免费、免Key、支持CORS，解码Base64字符串并返回原始内容',
    params: [
      {
        name: 'value',
        type: 'string',
        defaultValue: 'aGVsbG8=',
        required: true,
        description: '待解码的Base64字符串',
      },
    ],
    pinned: false,
  },
]
