export interface ApiParam {
  name: string
  type: 'string' | 'number' | 'boolean'
  defaultValue: string
  required: boolean
  description: string
}

export interface ApiItem {
  id: number
  name: string
  url: string
  method: 'GET' | 'POST'
  category: string
  description: string
  params: ApiParam[]
  createdAt: string
  pinned?: boolean
}

export const defaultApis: ApiItem[] = [
  {
    id: 1,
    name: '随机笑话',
    url: 'https://official-joke-api.appspot.com/random_joke',
    method: 'GET',
    category: '娱乐',
    description: '获取一个随机的英文笑话',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: '随机猫咪图片',
    url: 'https://api.thecatapi.com/v1/images/search',
    method: 'GET',
    category: '图片',
    description: '获取一张随机的猫咪图片',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: '随机狗狗图片',
    url: 'https://dog.ceo/api/breeds/image/random',
    method: 'GET',
    category: '图片',
    description: '获取一张随机的狗狗图片',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: '获取用户信息',
    url: 'https://jsonplaceholder.typicode.com/users/1',
    method: 'GET',
    category: '测试',
    description: '获取JSONPlaceholder的用户信息（测试用）',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: '随机名言',
    url: 'https://api.quotable.io/random',
    method: 'GET',
    category: '娱乐',
    description: '获取一条随机的名人名言',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: 'GitHub用户信息',
    url: 'https://api.github.com/users/{username}',
    method: 'GET',
    category: '开发',
    description: '通过用户名获取GitHub用户信息',
    params: [
      {
        name: 'username',
        type: 'string',
        defaultValue: 'octocat',
        required: true,
        description: 'GitHub用户名',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 7,
    name: '天气查询',
    url: 'https://wttr.in/{city}?format=j1',
    method: 'GET',
    category: '工具',
    description: '查询指定城市的天气信息',
    params: [
      {
        name: 'city',
        type: 'string',
        defaultValue: 'Beijing',
        required: true,
        description: '城市名称（英文）',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 8,
    name: 'IP地址查询',
    url: 'https://ipapi.co/{ip}/json/',
    method: 'GET',
    category: '工具',
    description: '查询IP地址的地理位置信息',
    params: [
      {
        name: 'ip',
        type: 'string',
        defaultValue: '',
        required: true,
        description: 'IP地址（留空则查询当前IP）',
      },
    ],
    createdAt: new Date().toISOString(),
  },

  {
    id: 9,
    name: '随机狐狸图片',
    url: 'https://randomfox.ca/floof/',
    method: 'GET',
    category: '图片',
    description: '返回一张随机狐狸图片的 URL（JSON）',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 10,
    name: '随机猫咪图片(Cataas)',
    url: 'https://cataas.com/cat?json=true',
    method: 'GET',
    category: '图片',
    description: '返回一张随机猫咪图片（JSON，含图片地址）',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 11,
    name: '随机动漫图片',
    url: 'https://nekos.life/api/v2/img/{type}',
    method: 'GET',
    category: '图片',
    description: '返回随机动漫图片 URL，type 可选 neko/kitsune 等',
    params: [
      {
        name: 'type',
        type: 'string',
        defaultValue: 'neko',
        required: true,
        description: '图片类型，如 neko/kitsune',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 12,
    name: '卡通头像(DiceBear)',
    url: 'https://api.dicebear.com/7.x/{style}/svg?seed={seed}',
    method: 'GET',
    category: '图片',
    description: '按 seed 生成卡通头像 SVG（style 可选 bottts/personas 等）',
    params: [
      {
        name: 'style',
        type: 'string',
        defaultValue: 'bottts',
        required: true,
        description: '头像风格，如 bottts/personas/adventurer',
      },
      {
        name: 'seed',
        type: 'string',
        defaultValue: 'demo',
        required: false,
        description: '随机种子，相同种子生成相同头像',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 13,
    name: '机器人头像(RoboHash)',
    url: 'https://robohash.org/{text}.png',
    method: 'GET',
    category: '图片',
    description: '按文本哈希生成机器人/怪物头像图片',
    params: [
      {
        name: 'text',
        type: 'string',
        defaultValue: 'demo',
        required: true,
        description: '用于生成头像的文本',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 14,
    name: '随机用户资料',
    url: 'https://randomuser.me/api/',
    method: 'GET',
    category: '图片',
    description: '返回随机用户资料（含头像 URL），可选 results/gender',
    params: [
      {
        name: 'results',
        type: 'number',
        defaultValue: '1',
        required: false,
        description: '返回用户数量',
      },
      {
        name: 'gender',
        type: 'string',
        defaultValue: '',
        required: false,
        description: '性别筛选，male/female',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 15,
    name: '必应每日壁纸',
    url: 'https://bing.biturl.top/?resolution=1920&format=json&index=0&mkt=zh-CN',
    method: 'GET',
    category: '图片',
    description: '返回当日必应壁纸图片地址与版权说明（国内可直连）',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 16,
    name: '爸爸冷笑话',
    url: 'https://icanhazdadjoke.com/',
    method: 'GET',
    category: '娱乐',
    description: '返回一条英文冷笑话（需 Accept: application/json，本应用默认已带）',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 17,
    name: '每日冷知识',
    url: 'https://uselessfacts.jsph.pl/api/v2/facts/random?language=en',
    method: 'GET',
    category: '娱乐',
    description: '返回一条无用的冷知识（英文）',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 18,
    name: '侃爷语录',
    url: 'https://api.kanye.rest',
    method: 'GET',
    category: '娱乐',
    description: '返回一句 Kanye West 随机语录',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 19,
    name: '随机生活建议',
    url: 'https://api.adviceslip.com/advice',
    method: 'GET',
    category: '娱乐',
    description: '返回一条随机生活建议',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 20,
    name: 'Ron Swanson 名言',
    url: 'https://ron-swanson-quotes.herokuapp.com/v2/quotes',
    method: 'GET',
    category: '娱乐',
    description: '返回一句 Ron Swanson 台词（数组）',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 21,
    name: '分类随机笑话',
    url: 'https://v2.jokeapi.dev/joke/Any?type=single',
    method: 'GET',
    category: '娱乐',
    description: '按分类返回随机笑话（single 两段式可选）',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 22,
    name: '猫咪趣味事实',
    url: 'https://meowfacts.herokuapp.com/?count=1',
    method: 'GET',
    category: '娱乐',
    description: '返回一条关于猫的趣味事实',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 23,
    name: '猫咪冷知识',
    url: 'https://catfact.ninja/fact',
    method: 'GET',
    category: '娱乐',
    description: '返回一条随机猫咪冷知识',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 24,
    name: '一言',
    url: 'https://v1.hitokoto.cn/?c=d',
    method: 'GET',
    category: '娱乐',
    description: '返回随机一句名言/语录，支持分类（国内可直连）',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 25,
    name: '今日诗词',
    url: 'https://v1.jinrishici.com/all.json',
    method: 'GET',
    category: '娱乐',
    description: '返回随机一句古诗文，含作者与出处（国内可直连）',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 26,
    name: 'IP 地理查询',
    url: 'https://ipwho.is/{ip}',
    method: 'GET',
    category: '工具',
    description: '按 IP 查询国家/城市/经纬度/时区（留空查本机）',
    params: [
      {
        name: 'ip',
        type: 'string',
        defaultValue: '',
        required: true,
        description: 'IP 地址，留空则查询当前 IP',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 27,
    name: '二维码生成',
    url: 'https://api.qrserver.com/v1/create-qr-code/?data={data}&size={size}',
    method: 'GET',
    category: '工具',
    description: '生成二维码 PNG 图片，data 为内容，size 如 200x200',
    params: [
      {
        name: 'data',
        type: 'string',
        defaultValue: 'https://vuechest.com',
        required: true,
        description: '二维码内容',
      },
      {
        name: 'size',
        type: 'string',
        defaultValue: '200x200',
        required: false,
        description: '尺寸，如 200x200',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 28,
    name: 'UUID 生成',
    url: 'https://www.uuidtools.com/api/generate/v1',
    method: 'GET',
    category: '工具',
    description: '返回随机 UUID 字符串数组',
    params: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 29,
    name: '姓名年龄预测',
    url: 'https://api.agify.io?name={name}',
    method: 'GET',
    category: '工具',
    description: '根据姓名预测年龄段',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'michael',
        required: true,
        description: '姓名',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 30,
    name: '姓名性别预测',
    url: 'https://api.genderize.io?name={name}',
    method: 'GET',
    category: '工具',
    description: '根据姓名预测性别',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'mary',
        required: true,
        description: '姓名',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 31,
    name: '姓名国籍预测',
    url: 'https://api.nationalize.io?name={name}',
    method: 'GET',
    category: '工具',
    description: '根据姓名预测最可能国籍',
    params: [
      {
        name: 'name',
        type: 'string',
        defaultValue: 'nathaniel',
        required: true,
        description: '姓名',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 32,
    name: '世界各国数据',
    url: 'https://restcountries.com/v3.1/name/{country}',
    method: 'GET',
    category: '数据',
    description: '按国家名查询国家信息（如首都、人口、旗帜）',
    params: [
      {
        name: 'country',
        type: 'string',
        defaultValue: 'china',
        required: true,
        description: '国家英文名，如 china',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 33,
    name: '开放图书馆检索',
    url: 'https://openlibrary.org/search.json?q={query}&limit={limit}',
    method: 'GET',
    category: '数据',
    description: '开放图书馆图书检索，返回书籍元数据',
    params: [
      {
        name: 'query',
        type: 'string',
        defaultValue: 'harry potter',
        required: true,
        description: '搜索关键词',
      },
      {
        name: 'limit',
        type: 'number',
        defaultValue: '5',
        required: false,
        description: '返回条数',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 34,
    name: '公共节假日查询',
    url: 'https://date.nager.at/api/v3/PublicHolidays/{year}/{countryCode}',
    method: 'GET',
    category: '数据',
    description: '查询指定年份与国家代码的公共节假日',
    params: [
      {
        name: 'year',
        type: 'string',
        defaultValue: '2025',
        required: true,
        description: '年份，如 2025',
      },
      {
        name: 'countryCode',
        type: 'string',
        defaultValue: 'CN',
        required: true,
        description: '国家代码，如 CN/US',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 35,
    name: '全球物种数据库',
    url: 'https://api.gbif.org/v1/species/{key}',
    method: 'GET',
    category: '数据',
    description: '全球物种数据库，按物种 key 查询信息',
    params: [
      {
        name: 'key',
        type: 'string',
        defaultValue: '1',
        required: true,
        description: '物种 key，如 1',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 36,
    name: '加密货币行情',
    url: 'https://api.coinbase.com/v2/prices/{pair}/spot',
    method: 'GET',
    category: '数据',
    description: '查询加密货币现货价格，pair 如 BTC-USD',
    params: [
      {
        name: 'pair',
        type: 'string',
        defaultValue: 'BTC-USD',
        required: true,
        description: '交易对，如 BTC-USD',
      },
    ],
    createdAt: new Date().toISOString(),
  },
]
